name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: julia-actions/setup-julia@v2
      with:
        version: 1
        arch: x86
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
