name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: 'pr56678'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
